# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(551, 712)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 60, 201, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.grpSize = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.grpSize.setContentsMargins(0, 0, 0, 0)
        self.grpSize.setObjectName("grpSize")
        self.radioSmall = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Mali")
        font.setPointSize(14)
        self.radioSmall.setFont(font)
        self.radioSmall.setObjectName("radioSmall")
        self.grpSize.addWidget(self.radioSmall)
        self.radioMedium = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Mali")
        font.setPointSize(14)
        self.radioMedium.setFont(font)
        self.radioMedium.setObjectName("radioMedium")
        self.grpSize.addWidget(self.radioMedium)
        self.radioLarge = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Mali")
        font.setPointSize(14)
        self.radioLarge.setFont(font)
        self.radioLarge.setObjectName("radioLarge")
        self.grpSize.addWidget(self.radioLarge)
        self.radioXlarge = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Mali")
        font.setPointSize(14)
        self.radioXlarge.setFont(font)
        self.radioXlarge.setObjectName("radioXlarge")
        self.grpSize.addWidget(self.radioXlarge)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 360, 211, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.grpPayType = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.grpPayType.setContentsMargins(0, 0, 0, 0)
        self.grpPayType.setObjectName("grpPayType")
        self.radioCard = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Mali")
        font.setPointSize(14)
        self.radioCard.setFont(font)
        self.radioCard.setObjectName("radioCard")
        self.grpPayType.addWidget(self.radioCard)
        self.radioPaypal = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Mali")
        font.setPointSize(14)
        self.radioPaypal.setFont(font)
        self.radioPaypal.setObjectName("radioPaypal")
        self.grpPayType.addWidget(self.radioPaypal)
        self.radioECheck = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Mali")
        font.setPointSize(14)
        self.radioECheck.setFont(font)
        self.radioECheck.setObjectName("radioECheck")
        self.grpPayType.addWidget(self.radioECheck)
        self.lblSize = QtWidgets.QLabel(Dialog)
        self.lblSize.setGeometry(QtCore.QRect(26, 9, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Mali")
        font.setPointSize(20)
        self.lblSize.setFont(font)
        self.lblSize.setObjectName("lblSize")
        self.lblPayType = QtWidgets.QLabel(Dialog)
        self.lblPayType.setGeometry(QtCore.QRect(30, 280, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Mali")
        font.setPointSize(20)
        self.lblPayType.setFont(font)
        self.lblPayType.setObjectName("lblPayType")
        self.lblSelected = QtWidgets.QLabel(Dialog)
        self.lblSelected.setGeometry(QtCore.QRect(30, 552, 491, 131))
        font = QtGui.QFont()
        font.setFamily("Mali")
        font.setPointSize(20)
        self.lblSelected.setFont(font)
        self.lblSelected.setText("")
        self.lblSelected.setWordWrap(True)
        self.lblSelected.setObjectName("lblSelected")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.radioSmall.setText(_translate("Dialog", "Small"))
        self.radioMedium.setText(_translate("Dialog", "Medium"))
        self.radioLarge.setText(_translate("Dialog", "Large"))
        self.radioXlarge.setText(_translate("Dialog", "X-Large"))
        self.radioCard.setText(_translate("Dialog", "Credit/Debit Card"))
        self.radioPaypal.setText(_translate("Dialog", "Paypal"))
        self.radioECheck.setText(_translate("Dialog", "Electronic check"))
        self.lblSize.setText(_translate("Dialog", "Select shirt size:"))
        self.lblPayType.setText(_translate("Dialog", "Select payment method:"))


