# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgSimpleCalc.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(562, 461)
        Dialog.setStyleSheet("background-color: rgb(252, 160, 255);\n"
"\n"
"\n"
"")
        self.txtOperandOne = QtWidgets.QLineEdit(Dialog)
        self.txtOperandOne.setGeometry(QtCore.QRect(160, 110, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Mali SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.txtOperandOne.setFont(font)
        self.txtOperandOne.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.txtOperandOne.setObjectName("txtOperandOne")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 110, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Mali SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 160, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Mali SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txtOperandTwo = QtWidgets.QLineEdit(Dialog)
        self.txtOperandTwo.setGeometry(QtCore.QRect(160, 160, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Mali SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.txtOperandTwo.setFont(font)
        self.txtOperandTwo.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.txtOperandTwo.setObjectName("txtOperandTwo")
        self.cmdAdd = QtWidgets.QPushButton(Dialog)
        self.cmdAdd.setGeometry(QtCore.QRect(40, 240, 75, 71))
        font = QtGui.QFont()
        font.setFamily("Mali SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmdAdd.setFont(font)
        self.cmdAdd.setStyleSheet("background-color: rgb(85, 0, 0);\n"
"color: white;")
        self.cmdAdd.setObjectName("cmdAdd")
        self.cmdDivide = QtWidgets.QPushButton(Dialog)
        self.cmdDivide.setGeometry(QtCore.QRect(340, 240, 75, 71))
        font = QtGui.QFont()
        font.setFamily("Mali SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmdDivide.setFont(font)
        self.cmdDivide.setStyleSheet("background-color: rgb(85, 0, 0);\n"
"color: white;")
        self.cmdDivide.setObjectName("cmdDivide")
        self.cmdMultiply = QtWidgets.QPushButton(Dialog)
        self.cmdMultiply.setGeometry(QtCore.QRect(240, 240, 75, 71))
        font = QtGui.QFont()
        font.setFamily("Mali SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmdMultiply.setFont(font)
        self.cmdMultiply.setStyleSheet("background-color: rgb(85, 0, 0);\n"
"color: white;")
        self.cmdMultiply.setObjectName("cmdMultiply")
        self.cmdSubtract = QtWidgets.QPushButton(Dialog)
        self.cmdSubtract.setGeometry(QtCore.QRect(140, 240, 75, 71))
        font = QtGui.QFont()
        font.setFamily("Mali SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmdSubtract.setFont(font)
        self.cmdSubtract.setStyleSheet("background-color: rgb(85, 0, 0);\n"
"color: white;")
        self.cmdSubtract.setObjectName("cmdSubtract")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 521, 41))
        font = QtGui.QFont()
        font.setFamily("Mali SemiBold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lblResult = QtWidgets.QLabel(Dialog)
        self.lblResult.setGeometry(QtCore.QRect(30, 360, 491, 71))
        font = QtGui.QFont()
        font.setFamily("Mali SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblResult.setFont(font)
        self.lblResult.setObjectName("lblResult")
        self.cmdClear = QtWidgets.QPushButton(Dialog)
        self.cmdClear.setGeometry(QtCore.QRect(440, 240, 75, 71))
        font = QtGui.QFont()
        font.setFamily("Mali SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmdClear.setFont(font)
        self.cmdClear.setStyleSheet("background-color: rgb(85, 0, 0);\n"
"color: white;")
        self.cmdClear.setObjectName("cmdClear")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "A Simple Calculator"))
        self.label.setText(_translate("Dialog", "Value One :"))
        self.label_2.setText(_translate("Dialog", "Value Two :"))
        self.cmdAdd.setText(_translate("Dialog", "+"))
        self.cmdDivide.setText(_translate("Dialog", "/"))
        self.cmdMultiply.setText(_translate("Dialog", "x"))
        self.cmdSubtract.setText(_translate("Dialog", "-"))
        self.label_3.setText(_translate("Dialog", "A Simple Calculator"))
        self.lblResult.setText(_translate("Dialog", "Your Results"))
        self.cmdClear.setText(_translate("Dialog", "C"))


