# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgIceCreamShop.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgIceCreamShop(object):
    def setupUi(self, dlgIceCreamShop):
        dlgIceCreamShop.setObjectName("dlgIceCreamShop")
        dlgIceCreamShop.resize(552, 602)
        self.label = QtWidgets.QLabel(dlgIceCreamShop)
        self.label.setGeometry(QtCore.QRect(110, 20, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Mali Medium")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(dlgIceCreamShop)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Mali Medium")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(dlgIceCreamShop)
        self.label_3.setGeometry(QtCore.QRect(10, 300, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Mali Medium")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lblTotal = QtWidgets.QLabel(dlgIceCreamShop)
        self.lblTotal.setGeometry(QtCore.QRect(10, 470, 491, 81))
        font = QtGui.QFont()
        font.setFamily("Mali Medium")
        font.setPointSize(26)
        self.lblTotal.setFont(font)
        self.lblTotal.setObjectName("lblTotal")
        self.grpIceCream = QtWidgets.QGroupBox(dlgIceCreamShop)
        self.grpIceCream.setGeometry(QtCore.QRect(220, 100, 281, 181))
        self.grpIceCream.setObjectName("grpIceCream")
        self.chkCookieDough = QtWidgets.QCheckBox(self.grpIceCream)
        self.chkCookieDough.setGeometry(QtCore.QRect(20, 140, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Mali Medium")
        font.setPointSize(10)
        self.chkCookieDough.setFont(font)
        self.chkCookieDough.setObjectName("chkCookieDough")
        self.chkMintChip = QtWidgets.QCheckBox(self.grpIceCream)
        self.chkMintChip.setGeometry(QtCore.QRect(20, 60, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Mali Medium")
        font.setPointSize(10)
        self.chkMintChip.setFont(font)
        self.chkMintChip.setObjectName("chkMintChip")
        self.chkRockyRoad = QtWidgets.QCheckBox(self.grpIceCream)
        self.chkRockyRoad.setGeometry(QtCore.QRect(20, 100, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Mali Medium")
        font.setPointSize(10)
        self.chkRockyRoad.setFont(font)
        self.chkRockyRoad.setObjectName("chkRockyRoad")
        self.chkSpumoni = QtWidgets.QCheckBox(self.grpIceCream)
        self.chkSpumoni.setGeometry(QtCore.QRect(20, 20, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Mali Medium")
        font.setPointSize(10)
        self.chkSpumoni.setFont(font)
        self.chkSpumoni.setObjectName("chkSpumoni")
        self.groupBox_2 = QtWidgets.QGroupBox(dlgIceCreamShop)
        self.groupBox_2.setGeometry(QtCore.QRect(220, 300, 281, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.chkScotch = QtWidgets.QCheckBox(self.groupBox_2)
        self.chkScotch.setGeometry(QtCore.QRect(20, 100, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Mali Medium")
        font.setPointSize(10)
        self.chkScotch.setFont(font)
        self.chkScotch.setObjectName("chkScotch")
        self.chkSoda = QtWidgets.QCheckBox(self.groupBox_2)
        self.chkSoda.setGeometry(QtCore.QRect(20, 60, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Mali Medium")
        font.setPointSize(10)
        self.chkSoda.setFont(font)
        self.chkSoda.setObjectName("chkSoda")
        self.chkCoffee = QtWidgets.QCheckBox(self.groupBox_2)
        self.chkCoffee.setGeometry(QtCore.QRect(20, 20, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Mali Medium")
        font.setPointSize(10)
        self.chkCoffee.setFont(font)
        self.chkCoffee.setObjectName("chkCoffee")

        self.retranslateUi(dlgIceCreamShop)
        QtCore.QMetaObject.connectSlotsByName(dlgIceCreamShop)

    def retranslateUi(self, dlgIceCreamShop):
        _translate = QtCore.QCoreApplication.translate
        dlgIceCreamShop.setWindowTitle(_translate("dlgIceCreamShop", "Dialog"))
        self.label.setText(_translate("dlgIceCreamShop", "Bobo\'s Ice Cream Shop"))
        self.label_2.setText(_translate("dlgIceCreamShop", "Choose your Ice Cream"))
        self.label_3.setText(_translate("dlgIceCreamShop", "Choose your beverage"))
        self.lblTotal.setText(_translate("dlgIceCreamShop", " "))
        self.grpIceCream.setTitle(_translate("dlgIceCreamShop", "Ice Cream"))
        self.chkCookieDough.setText(_translate("dlgIceCreamShop", "Cookie Dough $2.00"))
        self.chkMintChip.setText(_translate("dlgIceCreamShop", "Mint Chip $2.25"))
        self.chkRockyRoad.setText(_translate("dlgIceCreamShop", "Rocky Road $2.75"))
        self.chkSpumoni.setText(_translate("dlgIceCreamShop", "Spumoni $2.50"))
        self.groupBox_2.setTitle(_translate("dlgIceCreamShop", "Beverage"))
        self.chkScotch.setText(_translate("dlgIceCreamShop", "Scotch $3.00"))
        self.chkSoda.setText(_translate("dlgIceCreamShop", "Soda $1.25"))
        self.chkCoffee.setText(_translate("dlgIceCreamShop", "Coffee $1.50"))


